/* automatically generated by rust-bindgen 0.70.1 */

#[doc = " @brief This structure represents a pair of integers"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Pair {
    pub n: ::std::os::raw::c_int,
    pub m: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Pair"][::std::mem::size_of::<Pair>() - 8usize];
    ["Alignment of Pair"][::std::mem::align_of::<Pair>() - 4usize];
    ["Offset of field: Pair::n"][::std::mem::offset_of!(Pair, n) - 0usize];
    ["Offset of field: Pair::m"][::std::mem::offset_of!(Pair, m) - 4usize];
};
extern "C" {
    #[doc = " @brief This function performs the greatest common division (gcd) of a `Pair`\n\n @param i Minimum gcd to search for.\n @param ps Pair of integers to find the gcd.\n @return Greatest common divisor of `ps` that is larger or equal to `i`."]
    pub fn gcd(i: ::std::os::raw::c_int, ps: *mut Pair) -> ::std::os::raw::c_int;
}
