/* automatically generated by rust-bindgen 0.69.4 */

#[doc = " @brief This structure represents a pair of integers"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Pair {
    pub n: ::std::os::raw::c_int,
    pub m: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Pair() {
    const UNINIT: ::std::mem::MaybeUninit<Pair> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Pair>(),
        8usize,
        concat!("Size of: ", stringify!(Pair))
    );
    assert_eq!(
        ::std::mem::align_of::<Pair>(),
        4usize,
        concat!("Alignment of ", stringify!(Pair))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n) as usize - ptr as usize },
        0usize,
        concat!("Offset of field: ", stringify!(Pair), "::", stringify!(n))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m) as usize - ptr as usize },
        4usize,
        concat!("Offset of field: ", stringify!(Pair), "::", stringify!(m))
    );
}
extern "C" {
    #[doc = " @brief This function performs the greatest common division (gcd) of a `Pair`\n\n @param i Minimum gcd to search for.\n @param ps Pair of integers to find the gcd.\n @return Greatest common divisor of `ps` that is larger or equal to `i`."]
    pub fn gcd(i: ::std::os::raw::c_int, ps: *mut Pair) -> ::std::os::raw::c_int;
}
